### ISSUE TITLE
is rapidclipse a malware?

### ISSUE THREAD

**Issue by larrydalaw** [RapidClipse/xdev.server#1]
i have tried to reg as a user and dl the installation file but fail last year. as of now , i tried again, failed too.
but the account system said i am registered at register page, but when i log in , it says i m having bad password, but i click forgot pw,it returns to me acct not exist. 

my reg acct is wmg.lawrence@gmail.com ,

**Comment by GitMensch** [comment]
I think this one can be closed as it is about registering/login on a service (and is several months old), not at all about the RapidClipse Framework.

... thought it highlights an important point, see #2

**Comment by RapidClipse** [comment]
Issue not related to the RapidClipse Framework.
